import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import GifVideo from "@/components/ani";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Bookie",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="relative flex h-screen bg-black">
          {/* Background Video */}
          {/* <video
            className="absolute inset-0 w-full h-full object-cover"
            src="/background.mp4"
            autoPlay
            loop
            muted
          /> */}
          <GifVideo />
          
          {/* Overlay for Content */}
          <div className="absolute inset-0 bg-black/30"></div>

          {/* Navbar on the Left */}
          <div className="relative z-20 bg-black/70 text-white">
            <Navbar />
          </div>

          {/* Main Content on the Right */}
          <div className="relative z-10 flex-1 flex flex-col">
            {/* Main Content */}
            <main className="flex-1 p-8 overflow-y-auto text-white">
              {children}
            </main>

            {/* Text at Bottom
            <div className="bg-black/50 text-center text-white py-4">
              <p>Work of teemo</p>
            </div> */}
          </div>
        </div>
      </body>
    </html>
  );
}
